# Generated by Django 6.1.1 on 2026-10-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(help_text='VD: ambergris, handstay', unique=True)),
                ('logo', models.ImageField(upload_to='brands/logos/')),
                ('primary_color', models.CharField(default='#000000', help_text='Mã màu HEX (VD: Chamhouse là #9e4333)', max_length=7)),
                ('description', models.TextField(blank=True, verbose_name='Giới thiệu chung')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cơ sở')),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ cụ thể')),
                ('google_maps_iframe', models.TextField(blank=True, verbose_name='Mã nhúng Bản đồ')),
                ('hotline', models.CharField(blank=True, max_length=20)),
                ('zalo_link', models.URLField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hạng phòng')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tham khảo')),
                ('size_sqm', models.IntegerField(verbose_name='Diện tích (m2)')),
                ('max_guests', models.IntegerField(default=2, verbose_name='Số người tối đa')),
                ('description', models.TextField(verbose_name='Mô tả phòng')),
                ('cover_image', models.ImageField(upload_to='rooms/covers/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='core.property')),
            ],
        ),
    ]
