# Generated by Django 6.1.1 on 2026-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_maps_iframe',
            field=models.TextField(blank=True, help_text='Vào Google Maps > Bấm Chia sẻ (Share) > Chọn Nhúng bản đồ (Embed a map) > Copy mã HTML (bắt đầu bằng <iframe...) dán vào đây.', verbose_name='Mã nhúng Bản đồ'),
        ),
    ]
