# Generated by Django 6.1.1 on 2026-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_google_maps_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá khuyến mãi'),
        ),
    ]
