# Generated by Django 6.1.1 on 2026-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roomcategory_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AMBERGRIS', max_length=50, verbose_name='Tên Header')),
                ('footer_text', models.CharField(default='© 2026 Ambergris.', max_length=255, verbose_name='Chữ Footer')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Link Facebook')),
                ('hotline', models.CharField(blank=True, max_length=20, verbose_name='Hotline chung')),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
    ]
