# Generated by Django 6.1.1 on 2026-10-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='zalo_link',
            new_name='facebook_link',
        ),
    ]
