# Generated by Django 6.1.1 on 2026-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_zalo_link_property_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu chung'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu chung'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên thương hiệu'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên thương hiệu'),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='property',
            name='address_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên cơ sở'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên cơ sở'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Mô tả phòng'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Mô tả phòng'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên hạng phòng'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên hạng phòng'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text_en',
            field=models.CharField(default='© 2026 Ambergris.', max_length=255, null=True, verbose_name='Chữ Footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text_vi',
            field=models.CharField(default='© 2026 Ambergris.', max_length=255, null=True, verbose_name='Chữ Footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_en',
            field=models.CharField(default='AMBERGRIS', max_length=50, null=True, verbose_name='Tên Header'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_vi',
            field=models.CharField(default='AMBERGRIS', max_length=50, null=True, verbose_name='Tên Header'),
        ),
    ]
