# Generated by Django 6.1.1 on 2026-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_brand_description_en_brand_description_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ảnh nền Trang chủ'),
        ),
    ]
