# Generated by Django 6.1.1 on 2026-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting_homepage_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/backgrounds/', verbose_name='Ảnh nền Website (Full toàn trang)'),
        ),
    ]
