# Generated by Django 6.1.1 on 2026-10-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_property_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='calendar_iframe',
            field=models.TextField(blank=True, help_text='Vào Google Calendar > Settings > Integrate calendar > Copy mã Iframe dán vào đây', verbose_name='Mã nhúng Lịch Google'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Ảnh chi tiết')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.roomcategory')),
            ],
        ),
    ]
