# Generated by Django 6.1.1 on 2026-10-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_roomcategory_calendar_iframe_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sale_active',
            field=models.BooleanField(default=False, verbose_name='Bật chương trình Khuyến mãi'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ảnh nền Banner Sale'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_button_link',
            field=models.CharField(blank=True, help_text='Link trỏ đến bảng giá hoặc Zalo lễ tân', max_length=255, verbose_name='Link nút bấm (URL)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_button_text',
            field=models.CharField(blank=True, default='XEM BẢNG GIÁ NGAY', max_length=50, verbose_name='Chữ trên nút'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_description',
            field=models.TextField(blank=True, help_text='Nhập chi tiết giảm giá, tặng bữa sáng, welcome drink...', verbose_name='Mô tả & Tiện ích tặng kèm'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc (Đếm ngược)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sale_title',
            field=models.CharField(blank=True, default='CHƯƠNG TRÌNH MÙA LƯỜI', max_length=100, verbose_name='Tiêu đề Khuyến mãi'),
        ),
    ]
