# Generated by Django 6.1.1 on 2026-10-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesetting_sale_active_sitesetting_sale_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='weekend_surcharge',
            field=models.IntegerField(default=0, help_text='Số tiền cộng thêm vào Thứ 6, Thứ 7, Chủ Nhật', verbose_name='Phụ thu cuối tuần (VNĐ)'),
        ),
    ]
