# Generated by Django 6.1.1 on 2026-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_roomcategory_weekend_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ'),
        ),
    ]
