# Generated by Django 6.1.1 on 2026-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='promo_video_bg',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ảnh nền khu vực Video'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_video_url',
            field=models.URLField(blank=True, verbose_name='Link Video Giới thiệu (Youtube)'),
        ),
    ]
