# Generated by Django 6.1.1 on 2026-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesetting_promo_video_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_background_video',
            field=models.FileField(blank=True, help_text='Nếu upload Video, hệ thống sẽ ưu tiên dùng Video thay cho Ảnh nền', null=True, upload_to='backgrounds/videos/', verbose_name='Video nền Trang chủ (MP4)'),
        ),
    ]
