# Generated by Django 6.1.1 on 2026-10-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesetting_homepage_background_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Câu hỏi (VD: Có chỗ đậu xe không?)')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự ưu tiên')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.property')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp (FAQ)',
                'verbose_name_plural': 'Câu hỏi thường gặp (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
