# Generated by Django 6.1.1 on 2026-10-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='property',
        ),
        migrations.AddField(
            model_name='faq',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.brand'),
        ),
    ]
