# Generated by Django 6.1.1 on 2026-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_faq_property_faq_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='max_guests',
            field=models.CharField(default='2 Người lớn & 1 Trẻ em dưới 6 tuổi', max_length=150, verbose_name='Tiêu chuẩn khách'),
        ),
    ]
