# Generated by Django 6.1.1 on 2026-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_roomcategory_max_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tiện ích (VD: Wi-Fi Miễn phí)')),
                ('name_vi', models.CharField(max_length=100, null=True, verbose_name='Tên tiện ích (VD: Wi-Fi Miễn phí)')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Tên tiện ích (VD: Wi-Fi Miễn phí)')),
                ('icon', models.CharField(help_text='VD: bi-wifi. Tra cứu tại: https://icons.getbootstrap.com/', max_length=50, verbose_name='Mã Icon Bootstrap')),
            ],
            options={
                'verbose_name': 'Tiện ích',
                'verbose_name_plural': 'Các tiện ích',
            },
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='core.amenity', verbose_name='Các tiện ích có trong phòng'),
        ),
    ]
