# Generated by Django 6.1.1 on 2026-10-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_amenity_roomcategory_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='size_sqm',
        ),
    ]
