# Generated by Django 6.1.1 on 2026-10-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_roomcategory_max_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='name_vi',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_vi',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_vi',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_vi',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name_vi',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description_vi',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='name_vi',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_text_vi',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_name_vi',
        ),
    ]
