# Generated by Django 6.1.1 on 2026-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_amenity_icon_remove_amenity_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='checkin_time',
            field=models.CharField(default='14:00', max_length=50, verbose_name='Giờ Nhận phòng (Check-in)'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='checkout_time',
            field=models.CharField(default='12:00', max_length=50, verbose_name='Giờ Trả phòng (Check-out)'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='custom_policies',
            field=models.TextField(blank=True, help_text='Nếu có quy định riêng cho hạng phòng này (VD: Cấm trẻ em, Cấm mang sầu riêng...), ghi vào đây.', verbose_name='Chính sách & Lưu ý riêng (Tùy chọn)'),
        ),
    ]
