# Generated by Django 6.1.1 on 2026-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_roomcategory_checkin_time_roomcategory_checkout_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='calendar_iframe',
        ),
        migrations.AddField(
            model_name='property',
            name='google_sheet_credentials',
            field=models.FileField(blank=True, help_text='Upload file credentials.json của cơ sở này', null=True, upload_to='credentials/', verbose_name='File JSON Credentials (Google API)'),
        ),
        migrations.AddField(
            model_name='property',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='Chuỗi ký tự dài nằm giữa /d/ và /edit trong link Google Sheet', max_length=150, verbose_name='Google Sheet ID'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='sheet_row_name',
            field=models.CharField(blank=True, help_text='Nhập chính xác tên phòng ở cột A trong file Excel (VD: SUN POOL SUITE (R01))', max_length=150, verbose_name='Tên phòng trên Google Sheet'),
        ),
    ]
