# Generated by Django 6.1.1 on 2026-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_roomcategory_calendar_iframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='sheet_row_name',
            field=models.CharField(blank=True, help_text="1 phòng: 'ROOM A' | Nhiều phòng (Handstay): 'R1, R2, R3' | Phòng gộp (Connecting): 'R4 + R5'", max_length=150, verbose_name='Tên phòng trên Google Sheet'),
        ),
    ]
