# Generated by Django 6.1.1 on 2026-10-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_roomcategory_sheet_row_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Tiện ích', 'verbose_name_plural': '3. Các Tiện ích'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Thương hiệu', 'verbose_name_plural': '1. Các Thương hiệu'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Cơ sở (Chi nhánh)', 'verbose_name_plural': '2. Các Cơ sở (Chi nhánh)'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Hạng phòng', 'verbose_name_plural': '4. Các Hạng phòng'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Ảnh chi tiết phòng', 'verbose_name_plural': 'Ảnh chi tiết phòng'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Cấu hình Website', 'verbose_name_plural': '5. Cấu hình Website'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brands/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Mã màu HEX (VD: Chamhouse là #9e4333)', max_length=7, verbose_name='Màu chủ đạo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.brand', verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='property',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.brand', verbose_name='Thương hiệu trực thuộc'),
        ),
        migrations.AlterField(
            model_name='property',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='Link Facebook'),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_maps_iframe',
            field=models.TextField(blank=True, help_text='Vào Google Maps > Chia sẻ > Nhúng bản đồ > Copy iframe', verbose_name='Mã nhúng Bản đồ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='Chuỗi ký tự nằm giữa /d/ và /edit trong link Google Sheet', max_length=150, verbose_name='Google Sheet ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hotline',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hotline'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Đường dẫn (Slug)'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='cover_image',
            field=models.ImageField(upload_to='rooms/covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='custom_policies',
            field=models.TextField(blank=True, verbose_name='Chính sách & Lưu ý riêng (Tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='core.property', verbose_name='Cơ sở'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='sheet_row_name',
            field=models.CharField(blank=True, help_text="1 phòng: 'ROOM A' | Nhiều phòng (Handstay): 'R1, R2, R3' | Phòng gộp: 'R4 + R5'", max_length=150, verbose_name='Tên phòng trên Google Sheet'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.roomcategory', verbose_name='Hạng phòng'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='homepage_background_video',
            field=models.FileField(blank=True, help_text='Sẽ ưu tiên dùng Video thay cho Ảnh nền nếu có', null=True, upload_to='backgrounds/videos/', verbose_name='Video nền Trang chủ (MP4)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sale_button_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link nút bấm (URL)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='sale_description',
            field=models.TextField(blank=True, verbose_name='Mô tả & Tiện ích tặng kèm'),
        ),
    ]
