# Generated by Django 6.1.1 on 2026-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_amenity_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_active',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_background',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_button_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_description',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_end_date',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='sale_title',
        ),
        migrations.AddField(
            model_name='property',
            name='sale_active',
            field=models.BooleanField(default=False, verbose_name='Bật chương trình Khuyến mãi'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ảnh nền Banner Sale'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_button_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link nút bấm (URL)'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_button_text',
            field=models.CharField(blank=True, default='XEM BẢNG GIÁ NGAY', max_length=50, verbose_name='Chữ trên nút'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_description',
            field=models.TextField(blank=True, verbose_name='Mô tả & Tiện ích tặng kèm'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc (Đếm ngược)'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_title',
            field=models.CharField(blank=True, default='CHƯƠNG TRÌNH MÙA LƯỜI', max_length=100, verbose_name='Tiêu đề Khuyến mãi'),
        ),
    ]
