# Generated by Django 6.1.1 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_brand_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='disable_availability_check',
            field=models.BooleanField(default=False, help_text='Đánh dấu mục này để khóa người dùng tra cứu khi Google bị lỗi.', verbose_name='Bảo trì tính năng Tra cứu lịch trống'),
        ),
    ]
